// Generated by music_editor.html (dev tool): themes edited in the browser are
// saved here and override the composed versions in buildMusicThemes(), for the
// editor, the tests, and the render tool alike (the shipped game streams the
// remastered renders from public/audio/music/). Do not hand-edit: run
// npm run dev, open /music_editor.html, edit, and press Save.
import type { Theme } from './music';

export const MUSIC_OVERRIDES: Record<string, Theme> = {
};
