// Per-weapon in-game VFX tuning, written by the asset-pipeline inspector's
// "Save VFX" button (scripts/asset_pipeline/lib/integrate.mjs saveVfxTuning).
// Each row is the FULL slider state for that weapon: absolute multipliers over
// the authored spec, exactly what the inspector showed when saved. A row
// REPLACES the tier's WORLD_TUNING baseline (it does not stack on it), so the
// look dialed in the editor is the look that ships in the world renderer and
// the armory inspect preview. An absent key falls back to WORLD_TUNING[tier].
import { type WeaponVfxTierName, type WeaponVfxTuning, WORLD_TUNING } from './weapon_vfx';

export const WEAPON_VFX_TUNING: Record<string, Partial<WeaponVfxTuning>> = {
  // Populated by the inspector Save VFX button, keyed by weapon model basename.
  winterbite: {
    glow: 2,
    bloom: 0.3,
    light: 0.15,
    core: 1.35,
    aurora: 0.95,
    mist: 1.05,
    sparkle: 2,
    shell: 2,
    pool: 1.5,
  },
  starfall_judgment_of_the_heavens: {
    glow: 2,
    bloom: 0.35,
    light: 0.5,
    core: 0.7,
    motes: 0.75,
    aurora: 0.65,
    sparkle: 2,
    shell: 1.05,
  },
  skyrender_the_firmament_s_wound: {
    glow: 2,
    bloom: 0.95,
    light: 0.2,
    core: 2,
    motes: 2,
    aurora: 2,
    mist: 2,
    sparkle: 2,
    shell: 2,
    pool: 2,
  },
  astravyr_fang_of_the_fallen_star: {
    glow: 0.95,
    bloom: 0.65,
    light: 0,
    core: 2,
    motes: 2,
    aurora: 2,
    mist: 2,
    sparkle: 2,
    shell: 2,
    pool: 0.9,
  },
  cosmarch_spire_of_the_endless_void: {
    glow: 2,
    light: 0.55,
    core: 0.7,
    motes: 2,
    aurora: 2,
    sparkle: 2,
    shell: 2,
  },
  emberwish_mote_of_the_dying_sun: {
    glow: 2,
    bloom: 0.85,
    light: 0.4,
    core: 0,
    motes: 2,
    aurora: 2,
    mist: 2,
    sparkle: 2,
    shell: 2,
    pool: 0.85,
  },
  frostbite: {
    glow: 1.95,
    bloom: 0,
    light: 0.4,
    core: 2,
    motes: 0.7,
    mist: 0.6,
    sparkle: 0.65,
    shell: 2,
  },
  glaciersplit: {
    glow: 2,
    bloom: 1.1,
    light: 0.6,
    core: 0.15,
    motes: 0.85,
    aurora: 0.8,
    mist: 0.6,
    sparkle: 2,
    shell: 2,
  },
  ice_fang: {
    glow: 2,
    bloom: 0.4,
    light: 0.8,
    core: 2,
    motes: 0.7,
    aurora: 1.75,
    mist: 0.6,
    sparkle: 2,
    shell: 2,
    pool: 0.9,
  },
  meteorlatch_the_sky_s_last_judgment: {
    glow: 2,
    bloom: 0.25,
    light: 0.5,
    core: 2,
    motes: 2,
    aurora: 2,
    sparkle: 2,
    shell: 2,
    pool: 0.65,
  },
  rimecrusher: { glow: 2, light: 0.5, core: 0.65, motes: 0.7, mist: 0.6, sparkle: 2, shell: 2 },
  rude_awakening_sword: {
    glow: 2,
    bloom: 0.3,
    light: 0.75,
    core: 2,
    motes: 2,
    aurora: 2,
    mist: 2,
    sparkle: 2,
    shell: 2,
  },
  shard_of_everwinter: {
    glow: 2,
    bloom: 0.85,
    light: 0.25,
    core: 0.65,
    motes: 2,
    mist: 0.6,
    sparkle: 2,
    shell: 2,
  },
  solheim_last_light_of_the_dawn: {
    glow: 0.6,
    light: 0.55,
    core: 0.7,
    motes: 0.75,
    aurora: 0.65,
    sparkle: 0.7,
    shell: 0.55,
  },
  hoarfrost_vigil: {
    glow: 2,
    bloom: 0.35,
    light: 0.7,
    core: 0.65,
    motes: 2,
    mist: 1.45,
    sparkle: 2,
    shell: 2,
  },
  encore_the_second_falling_star: {
    glow: 2,
    bloom: 0.65,
    light: 0.25,
    core: 0.7,
    motes: 2,
    aurora: 2,
    mist: 2,
    sparkle: 2,
    shell: 2,
  },
};

/** Effective in-game tuning for a skinned weapon: the hand-saved per-weapon
 *  row when one exists, else the tier's world softening baseline. */
export function weaponVfxTuningFor(
  model: string,
  tier: WeaponVfxTierName,
): Partial<WeaponVfxTuning> {
  return WEAPON_VFX_TUNING[model] ?? WORLD_TUNING[tier] ?? {};
}
