// Bakes every zone's world-map terrain background into a static WebP plate
// (public/map_bg/<zoneId>.webp) plus the generated manifest the runtime gates
// on (src/ui/map_bg_manifest.generated.ts). The plates are pure functions of
// (world seed, zone bounds), and the shipped world seed is fixed, so painting
// ~360k pixels of terrain per zone on every client at runtime was pure waste:
// with a plate the client only decodes an image. The procedural painter stays
// as the fallback for custom seeds, edited worlds, and missing plates.
//
// Run via `npm run assets:mapbg` after ANY world-generation change (the
// freshness guard tests/map_bg_baked.test.ts reds until you do). Mirrors the
// esbuild-bundle pattern in scripts/wiki/build_content.mjs (never import raw
// .ts from an .mjs).
import fs from 'node:fs';
import path from 'node:path';
import * as esbuild from 'esbuild';
import sharp from 'sharp';

const root = process.cwd();
const WORLD_SEED = 20061; // src/main.ts WORLD_SEED (the fixed persistent world)
// Plate width now follows the zone (mapPlateWidth): the plates cover the square
// the map window frames, and a zone's square is wider than its rectangle, so a
// single width for every zone would have thinned the detail inside the zone by
// the same factor it widened the view. This is INDEPENDENT of MAP_BG_RES, the
// resolution the runtime's procedural fallback paints at: the plate is blitted
// scaled either way, so baking sharper costs the fallback nothing.
const HASH_ROWS = 16; // freshness fingerprint rows (see hashPaintedRows)

const entrySource = `
  export { WORLD_MAX_X, WORLD_MAX_Z, WORLD_MIN_X, WORLD_MIN_Z, ZONES } from './src/sim/data.ts';
  export {
    MAP_PLATE_PX_PER_YD,
    mapCanvasHeight,
    mapPlateWidth,
    mapZoneRegion,
    hashPaintedRows,
    paintTerrainRows,
  } from './src/ui/map_terrain.ts';
`;

const built = await esbuild.build({
  stdin: {
    contents: entrySource,
    resolveDir: root,
    sourcefile: 'map-bg-entry.ts',
    loader: 'ts',
  },
  bundle: true,
  platform: 'node',
  format: 'esm',
  write: false,
  logLevel: 'silent',
});
const dataUrl = `data:text/javascript;base64,${Buffer.from(built.outputFiles[0].text).toString('base64')}`;
const {
  WORLD_MAX_X,
  WORLD_MAX_Z,
  WORLD_MIN_X,
  WORLD_MIN_Z,
  ZONES,
  MAP_PLATE_PX_PER_YD,
  mapCanvasHeight,
  mapPlateWidth,
  mapZoneRegion,
  hashPaintedRows,
  paintTerrainRows,
} = await import(dataUrl);

const outDir = path.join(root, 'public', 'map_bg');
fs.mkdirSync(outDir, { recursive: true });

const zones = {};
for (const zone of ZONES) {
  const region = mapZoneRegion(zone);
  const W = mapPlateWidth(region);
  const H = mapCanvasHeight(W, region);
  const data = new Uint8ClampedArray(W * H * 4);
  const started = Date.now();
  paintTerrainRows(data, W, H, region, WORLD_SEED, 0, H);
  const file = path.join(outDir, `${zone.id}.webp`);
  await sharp(Buffer.from(data.buffer), { raw: { width: W, height: H, channels: 4 } })
    .webp({ quality: 88 })
    .toFile(file);
  zones[zone.id] = {
    w: W,
    h: H,
    rowHash: hashPaintedRows(region, WORLD_SEED, W, HASH_ROWS),
  };
  const kb = Math.round(fs.statSync(file).size / 1024);
  console.log(`baked ${zone.id}: ${W}x${H} ${kb}KB in ${Date.now() - started}ms`);
}

// The minimap's whole-world strip (140px wide today) bakes as one extra
// plate, sea between the zones included, so the HUD's synchronous boot render
// of ~50k terrain pixels becomes an image decode too.
const MINIMAP_W = 140;
{
  const region = { minX: WORLD_MIN_X, maxX: WORLD_MAX_X, minZ: WORLD_MIN_Z, maxZ: WORLD_MAX_Z };
  const H = mapCanvasHeight(MINIMAP_W, region);
  const data = new Uint8ClampedArray(MINIMAP_W * H * 4);
  const started = Date.now();
  paintTerrainRows(data, MINIMAP_W, H, region, WORLD_SEED, 0, H);
  const file = path.join(outDir, 'world_strip.webp');
  await sharp(Buffer.from(data.buffer), { raw: { width: MINIMAP_W, height: H, channels: 4 } })
    .webp({ quality: 88 })
    .toFile(file);
  zones.world_strip = {
    w: MINIMAP_W,
    h: H,
    rowHash: hashPaintedRows(region, WORLD_SEED, MINIMAP_W, HASH_ROWS),
  };
  console.log(`baked world_strip: ${MINIMAP_W}x${H} in ${Date.now() - started}ms`);
}

const manifestPath = path.join(root, 'src', 'ui', 'map_bg_manifest.generated.ts');
const manifest = `// GENERATED by scripts/build_map_backgrounds.mjs; do not edit by hand.
// Re-bake with \`npm run assets:mapbg\` after any world-generation change
// (tests/map_bg_baked.test.ts guards freshness). Plates live in public/map_bg/.

export const BAKED_MAP_BG = {
  seed: ${WORLD_SEED},
  pxPerYd: ${MAP_PLATE_PX_PER_YD},
  hashRows: ${HASH_ROWS},
  zones: ${JSON.stringify(zones, null, 2)},
} as const;
`;
fs.writeFileSync(manifestPath, manifest);
console.log(`wrote ${manifestPath} (${Object.keys(zones).length} zones)`);
